import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">SortbyPopupwithspace</Link>
        </li>
        <li>
          <Link to="/workflow">Workflow</Link>
        </li>
        <li>
          <Link to="/selectproject">Selectproject</Link>
        </li>
        <li>
          <Link to="/listactionssortbyp">ListActionsSortbyp</Link>
        </li>
        <li>
          <Link to="/cardfilterwithspaceco">CardFilterwithspaceco</Link>
        </li>
        <li>
          <Link to="/filter">Filter</Link>
        </li>
        <li>
          <Link to="/savefilter">SaveFilter</Link>
        </li>
        <li>
          <Link to="/savefilterone">SaveFilterOne</Link>
        </li>
        <li>
          <Link to="/delete">Delete</Link>
        </li>
        <li>
          <Link to="/viewpopup">Viewpopup</Link>
        </li>
        <li>
          <Link to="/pinnedcardpopup">PinnedCardPopup</Link>
        </li>
        <li>
          <Link to="/archivedcardpopup">ArchivedCardPopup</Link>
        </li>
        <li>
          <Link to="/snoozecardpopup">SnoozecardPopup</Link>
        </li>
        <li>
          <Link to="/iconlibrary">IconLibrary</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
